service: countries

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:740360966654:table/countries

params:
  default:
    folderPath: ""
  prod:
    folderPath: /tmp

functions:
  getReportCountry:
    handler: src/functions/reports/route.handler
    events:
      - httpApi: GET /report
    environment:
      MAIN_PATH: ${param:folderPath}
    timeout: 20
  swagger:
    handler: src/functions/api-docs/route.handler
    events:
      - httpApi: GET /
    environment:
      URL: https://u5xi75eut1.execute-api.us-east-2.amazonaws.com
  getCountries:
    handler: src/functions/retrive-countries/route.handler
    events:
      - httpApi: GET /countries
    timeout: 20

resources:
  Resources:
    countriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: countries
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-tscpaths
